# Generated by Django 4.1.5 on 2023-01-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="abstract",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="ending_page",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="article",
            name="issue",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="journal_abbr",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="number",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="starting_page",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="volume",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="abstract",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="link_github",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="link_project",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="abstract",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="link_abstract",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="link_content",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="publication",
            name="month",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="publication",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="software",
            name="abstract",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="software",
            name="link_github",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="software",
            name="link_project",
            field=models.URLField(blank=True, null=True),
        ),
    ]
