# Generated by Django 4.1.5 on 2023-01-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_article_abstract_alter_article_ending_page_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publication",
            old_name="image",
            new_name="cover_image",
        ),
        migrations.RemoveField(
            model_name="instrument",
            name="link_github",
        ),
        migrations.RemoveField(
            model_name="software",
            name="link_github",
        ),
        migrations.AddField(
            model_name="article",
            name="doi",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="link_url",
            field=models.URLField(default="defaul"),
            preserve_default=False,
        ),
    ]
