# Generated by Django 4.1.5 on 2023-03-01 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_rename_image_publication_cover_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Oraltalks",
            fields=[
                (
                    "publication_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="base.publication",
                    ),
                ),
                ("event_name", models.CharField(max_length=100)),
                ("event_abbr", models.CharField(max_length=50)),
                ("presentation_date", models.DateField(blank=True)),
                ("address", models.CharField(max_length=500)),
                ("abstract", models.TextField(blank=True, max_length=500, null=True)),
                ("link_abstract", models.URLField(blank=True, null=True)),
                ("link_content", models.URLField(blank=True, null=True)),
            ],
            bases=("base.publication",),
        ),
        migrations.RenameModel(
            old_name="Presentation",
            new_name="Banner",
        ),
        migrations.AlterModelOptions(
            name="publication",
            options={"ordering": ["year"]},
        ),
        migrations.RenameField(
            model_name="banner",
            old_name="address",
            new_name="description",
        ),
        migrations.AlterField(
            model_name="publication",
            name="cover_image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
