# Generated by Django 4.1.5 on 2023-03-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_oraltalks_rename_presentation_banner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="description",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="banner",
            name="presentation_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
