# Generated by Django 4.1.5 on 2023-03-01 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_oraltalks_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Data_analysis",
            fields=[
                (
                    "publication_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="base.publication",
                    ),
                ),
                ("link_project", models.URLField(blank=True, null=True)),
                ("description", models.TextField(max_length=500)),
            ],
            bases=("base.publication",),
        ),
        migrations.RemoveField(
            model_name="instrument",
            name="abstract",
        ),
        migrations.RemoveField(
            model_name="software",
            name="abstract",
        ),
        migrations.AddField(
            model_name="instrument",
            name="description",
            field=models.TextField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="instrument",
            name="link_github",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="software",
            name="description",
            field=models.TextField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="instrument",
            name="link_project",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
    ]
